### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by bagobor** [sencercoltu/steamvr-undistort#1]
I'm getting the error:
>  'OpenVR' does not contain a definition for 'RuntimePath' with latest OpenVR files. 

On line:
`var ovrPath = OpenVR.RuntimePath();`

Witch version are you using?

**Comment by sencercoltu** [comment]
version 1.0.16, but the function is missin in the .cs file.
you need to add it manually to the cs file.

https://github.com/ValveSoftware/openvr/pull/876/commits/814badf2acbb4f57b246a100db3d4ce8cd0288b0

**Comment by bagobor** [comment]
@sencercoltu thank you!
