### ISSUE TITLE
Will this only work with the vive or other steamvr hmd’s?

### ISSUE THREAD

**Issue by Aesop112** [sencercoltu/steamvr-undistort#2]
With the pimax 8k steamvr hmd coming soon with a 170f field of view it’d be cool if one could modify the lens distortion profile for it.

**Comment by sencercoltu** [comment]
Currently Vive and SteamTrackingHDK devices only, cannot add pimax support without owning one :(

**Comment by valtersboze** [comment]
Have u got pimax yet?
Im using pimax. Would it be possible to disable distortion completely to have sharp image like XTAL does?

**Comment by sencercoltu** [comment]
Got my Pimax, but seems the pimax driver doesn't use openvr's distortion correction functions. Also, dumping the lighthouse config of pimax reveals that coeffs are not set in the json file. Distortion correction seems to be hardcoded in the driver or the headset. I short, this project won't work with the Pimax Headset.
