### ISSUE TITLE
0.1.7 .exe doesn't open

### ISSUE THREAD

**Issue by NoahWL** [sencercoltu/steamvr-undistort#4]
For some reason the Undistort.exe file does nothing upon double-clicking it.  I've tried re-downloading, running as admin, and running in compatibility mode for Windows 7 and 8.  0.1.6 does the same, I haven't tried the others.

I'm on Windows 10 x64, R7 2700x, 1080 Ti.  Is there a debug log generated somewhere that I can upload here?  I didn't see anything generated in the folder I had the exe in, nor an output when running it through cmd.  Also, strangely enough, downloading the source and running it through Visual Studio gives me no issues.  So the program does work on my PC in its current state, just not through the executable.

If it matters at all, I was able to get a previous version working before the DX11 debug fixes were introduced.  I actually settled on the same exact solution added [here](https://github.com/sencercoltu/steamvr-undistort/commit/3c390e3bae7ddf413a853808a19f419d53815af9#diff-34cffdae1474e839ffac88fe019a0155L449) before I realized it was updated, lol.

**Comment by sencercoltu** [comment]
you need to download a previous full release, which contains all the dll's and models. 0.1.7 is the  exe only.

**Comment by sencercoltu** [comment]
Maybe a file is missing. Have you unpacked the 0.1.4 zip and extracted the 0.1.7 exe inside the folder?
I will add an exception/debug log to see what is going on.
Does the .exe run after release compiling it on your machine?

**Comment by NoahWL** [comment]
Ah, I have not done so.  I mistook “exe only” for stand-alone so I didn’t have any of the other necessary files.  Thanks!
