### ISSUE TITLE
How do you uninstall this thing?!

### ISSUE THREAD

**Issue by stereodanny** [sencercoltu/steamvr-undistort#5]
I tried running this program and now my SteamVR won't launch (error 308) I've tried deleting openvr.dll and the folder in the AppData folder but it just recreates the files and crashes Steam. Please, what are the uninstall instructions?

**Comment by sencercoltu** [comment]
It doesn't install anything like a driver that will interfere with SteamVR on startup, but if you have overwritten your original Vive lens config, there should be a LH_Config_In.XXX.backup.json in your programs folder. Use lighthouse_console.exe in the Steam\steamapps\common\SteamVR\tools\lighthouse\bin\win(64/86) folder and upload it with command uploadconfig <full_path_to_LH_Config_In.XXX.backup.json>
The reboot your HMD, or even better unplug the power of the controlbox.
