### ISSUE TITLE
0.1.8 drops a dictionary key error

### ISSUE THREAD

**Issue by farlight1** [sencercoltu/steamvr-undistort#6]
After launching the .exe it popups an error dialog box with "the given key was not found in the dictionary" and then exits.

The file Debug.log contains:
Exception: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
Exception: System.UnhandledExceptionEventArgs

**Comment by sencercoltu** [comment]
I'll look into this. What HMD do you have? Vive?

**Comment by farlight1** [comment]
yes Vive + win10 pro 1809 build
I also installed the win10 graphics tools and .Net 4.7.2 framework with same result.

**Comment by sencercoltu** [comment]
I accidentally used a wrong model in previous release. Fixed that now in v0.1.9 release. (.exe only)
I also added stacktrace and innerexception to debug log, if fixing the model path doesn't solve the issue.

**Comment by farlight1** [comment]
I already test the new .exe, it drops same error dialog box.
Now the debug.log file shows:

Exception: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
Exception: System.UnhandledExceptionEventArgs    en System.ThrowHelper.ThrowKeyNotFoundException()
   en System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   en Undistort.Program.LoadLHSettings(String ovrPath)
   en Undistort.Program.Main()  

The LH_Config_In.json is updated on every time I launch the program, messing with the file, I realized that is not in the same estructure as the one you provide with the .zip, take a look, I attached the file here. Maybe a HTC/Valve update?

[LH_Config_In_1.txt](https://github.com/sencercoltu/steamvr-undistort/files/3094415/LH_Config_In_1.txt)

**Comment by sencercoltu** [comment]
Some config keys were missing in the file you provided. (aspect, persistence and extrinsics.)
They weren't used in the code anyway, so I removed loading the keys.
v0.1.10 should work for you now.

**Comment by farlight1** [comment]
I tried v0.1.10, last error gone, but now shows another one in SharpDX:

Exception: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
Exception: System.UnhandledExceptionEventArgs    en SharpDX.Result.CheckError()
   en SharpDX.Direct3D11.Device.CreateBuffer(BufferDescription& descRef, Nullable`1 initialDataRef, Buffer bufferOut)
   en SharpDX.Direct3D11.Buffer..ctor(Device device, Int32 sizeInBytes, ResourceUsage usage, BindFlags bindFlags, CpuAccessFlags accessFlags, ResourceOptionFlags optionFlags, Int32 structureByteStride)
   en Undistort.Program.Main() 

I tried to complete missing keys in the .json file with ones of your sample file, and then upload the file back to the HDM, and v0.1.9 runs OK! (I also tried v0.1.10 after, but fails with same error above).
I don't know why my HDM had a diferent config schema, but this tunned one seems to works fine.

Thanks4all, I'll put back Gear VR lens and mess around with distortion :)

**Comment by sencercoltu** [comment]
Interesting, there was nothing changed in the DX code. I'll double check later.
You'll newer be able to find the perfect distortion coefficients with this tool, because the GearVR lenses are not perfectly spherical. You'll get acceptable results, but don't spend too much time on it.  Good news is that I'm working on a new distortion correction solution. No more config file uploading will be needed with this one, and it can be used with any lens, not just GearVR. Stay tuned ^^.

**Comment by farlight1** [comment]
Oh!, that's will be great, this version already helps a lot, I can´t wait for the new one.
Awesome work 👍

**Comment by GrodenVR** [comment]
Wow, that's exciting! 
btw I just received the Nintendo Labo VR lenses - I'm going to test them out with the vive. They are huge and have a very fine Fresnel pattern similar to the Oculus Go lenses.

**Comment by sencercoltu** [comment]
@farlight1 I fixed the D3D error.

**Comment by farlight1** [comment]
The latest release runs fine, no problems at all.
thanks @sencercoltu
