### ISSUE TITLE
Live distortion correction preview seems to be a little off

### ISSUE THREAD

**Issue by synthead** [sencercoltu/steamvr-undistort#9]
When I load the utility and make no changes, I am able to observe different distortion compensation between the original view and the corrected preview.  For example, I am able to get all the "c" settings dialed in perfectly in the preview, but after writing and rebooting SteamVR, I am able to see reds and blues on the edges of objects in the mids and edges of my vision.

On about Feb 2nd (2020), I noticed that the distortion was slightly off.  Maybe it has to do with a SteamVR update?  Perhaps reprojection plays into it, somehow?  I thought it was from physically shifting the lenses from cleaning them often, but after finding that the distortion preview wasn't identical, I wonder if it's a software thing.  I remember the preview being exactly correct in the past.

**Comment by sencercoltu** [comment]
Hi, nothing has changed on the software side. 
Previously there was a slight shift in channels, after adding a  wavelength coefficient constant to red and blue channels coefficients inside the shader, the shift was gone. Maybe it's not needed anymore after the Feb update. Since I switched to Pimax, I won't be able to check the issue easily soon.

**Comment by synthead** [comment]
If I used [this release](https://github.com/sencercoltu/steamvr-undistort/releases/tag/v0.1.8), and the problem goes away, would it confirm this issue?

**Comment by synthead** [comment]
Hey @sencercoltu, I reverted the constants in https://github.com/sencercoltu/steamvr-undistort/commit/a49c7c30a15e09a9a7a7b0144af87c4d2189e502, and the shader looks identical to the original view now!  I think they fixed something upstream.

I opened a PR for you! https://github.com/sencercoltu/steamvr-undistort/pull/10  Let me know how it looks, and thanks again for this awesome tool!
